#!/bin/bash

remote="aranb@users.emulab.net"
remote_dir="/proj/End2end/loctx/out/"

rsync -zav ${remote}:${remote_dir} ${HOME}/out-emulab

#ssh -T ${remote} <<EOF
#	cd ${remote_dir}
#	zip outmaster *[^zip]
#EOF

#scp ${remote}:${remote_dir}/outmaster.zip ~/out-emulab
#cd ~/out-emulab
#unzip outmaster

