#!/bin/bash


if [ "$#" -lt 1 ]
then
	echo "Usage: `basename $0` output-file title <list of label:prefix>"
	exit 1
fi
export output=$1
shift
export title=$1; shift
export prefnum=$#
export prefixes=$@
export col=7 # Singleton Latency column
export txncol=10 # Transaction Latency column
export updatecol=5
export readcol=6

unset outfiles
for i in ${prefixes}; do
	outfiles="${outfiles[@]} ${i#*:}.out" 
	labels="${labels[@]} ${i%%:*}"
	if [[ ${i%%:*} == *"Txn"* ]]; then
		curcol=$txncol
	else
		curcol=$col
	fi
	if [[ ${i%%:*} == *"HBase"* ]]; then
		if [[ ${i%%:*} == *"Read"* ]]; then
			curcol=$readcol
		else
			curcol=$updatecol
		fi
	fi
	cols="${cols[@]} $curcol"
	if [[ ${i%%:*} == *"Mix"* ]]; then
		th_div=2
	else	
		th_div=2
	fi
	th_divs="${th_divs[@]} $th_div"
done;


gnuplot -persist << EOF
	outfiles="${outfiles}"
	labels="${labels}"
	cols="${cols}"
	th_divs="${th_divs}"
	set style line 1 lt 1 lc rgb '#0072bd' lw 2 pt 5 ps 1.5 # blue
	set style line 6 lt 1 lc rgb '#d95319' lw 2 pt 6 ps 1.5 # orange
	set style line 5 lt 1 lc rgb '#edb120' lw 2 pt 7 ps 1.5 # yellow
	set style line 4 lt 1 lc rgb '#7e2f8e' lw 2 pt 8 ps 1.5 # purple
	set style line 3 lt 1 lc rgb '#77ac30' lw 2 pt 9 ps 1.5 # green
	set style line 7 lt 1 lc rgb '#4dbeee' lw 2 pt 10 ps 1.5 # light-blue
	set style line 2 lt 1 lc rgb '#a2142f' lw 2 pt 11 ps 1.5 # red
	#set style line 1 lc rgb '#0060ad' lt 1 lw 2 pt 7 ps 1.5   # --- blue
	#set style line 2 lc rgb '#dd181f' lt 1 lw 2 pt 5 ps 1.5   # --- red
	set key left top
	set xlabel "Throughput"
	set ylabel 'Latency [us]'
	set title "${title}"
	set terminal pngcairo
	set output "${output}"
	#set yrange [:5]
	#set xrange [:600]
	plot for [i=1:${prefnum}] word(outfiles,i) using (\$2/word(th_divs,i)):0+word(cols,i) with linespoints ls i title word(labels,i)
EOF
 
